language: node_js

node_js:
  - "node"
  - "10"
  - "9"

script:
  - npm run build
  - npm test -- --coverage
  - npx codecov

deploy:
  - provider: script
    skip_cleanup: true
    script: npx travis-deploy-once "npx semantic-release"
